PRAGMA FOREIGN_KEYS = ON
;

CREATE TABLE IF NOT EXISTS SOMETHING (
  ID INTEGER PRIMARY KEY ASC,
  OTHERID INTEGER,
  DATA INTEGER,
  FOREIGN KEY (OTHERID) REFERENCES OTHER (ID)
)
;

CREATE TABLE IF NOT EXISTS OTHER (
  ID INTEGER PRIMARY KEY ASC,
  DATA VARCHAR(40) UNIQUE
)
;